### ISSUE TITLE
OpenGraph image for web site

### ISSUE THREAD

**Issue by benvinegar** [benvinegar/counterscale#10]
It would be nice if the website returned an OpenGraph image of some kind.

**Comment by TatisLois** [comment]
Would be cool to give this a shot, I have some free time and would like to help out. 

Did you have anything in mind or can I come with an initial attempt?

**Comment by benvinegar** [comment]
I think for this one it's really about just making an image with your favorite pixel editing tool in the correct dimensions (incorporating the existing logo, colors, and font somehow), making that image file available it in `/public`, then putting the right meta tags inside the root layout (`root.tsx`).

You're welcome to give it a shot! Just be forewarned I'm particular about the look and feel of this stuff and might edit or change the image afterwards.

![](https://github.com/benvinegar/counterscale/raw/main/public/counterscale-logo-300x300.webp)

**Comment by TatisLois** [comment]
Hey @benvinegar - I had a few ideas on how the open graph images could be even more useful but did not want to over engineer a first pass. 

Before I adding the images to the application, I wanted to get feedback on the design. What do you think, is this good enough to add?

Here is a figma with my first pass in different open graph sizes: 
https://www.figma.com/file/HOWGAppSjDGL36RdjvO3Ms/Counterscale-Open-Graph?type=design&mode=design&t=xtr53zvb3Ch7cudg-1

**Comment by benvinegar** [comment]
@TatisLois Oof, sorry, I never saw the email notification for your comment here – only just saw it now. 😔

> What do you think, is this good enough to add?

I think these look awesome and thank you for putting them together. If I haven't zapped all your motivation to continue, it'd be awesome to serve these up as OG images. I'm also cool to take what you've made and put it in. Let me know.

**Comment by TatisLois** [comment]
No worries @benvinegar only happy that they worked out. I'll find another issue to help out, glad this was merged 🙂
