### ISSUE TITLE
Add horizontal bar chart / visual indicator to card rows

### ISSUE THREAD

**Issue by benvinegar** [benvinegar/counterscale#28]
Most products in this space use horizontal bar charts - in addition to counts - to help visually indicate how "big" a bucket is.

Example from Plausible's marketing page:

![image](https://github.com/benvinegar/counterscale/assets/2153/09d60fe2-c52a-4d1d-b259-1b9f889ee2e9)

Counterscale at the moment:

![image](https://github.com/benvinegar/counterscale/assets/2153/35fcdcf6-1a31-480d-bad3-d9846031f0db)

**Comment by chiubaca** [comment]
Can I work on this?

**Comment by benvinegar** [comment]
> Can I work on this?

100%

**Comment by chiubaca** [comment]
https://github.com/benvinegar/counterscale/pull/39 ready for review 😄
