### ISSUE TITLE
Add "today" and "yesterday" as date range choices

### ISSUE THREAD

**Issue by benvinegar** [benvinegar/counterscale#3]
Right now it's just "past 1 day" / previous 24 hours. Today should mean from 00:00 this morning to now. Yesterday should mean 00:00 to 23:59 yesterday.

Edit: As of #53 it supports "today", so only "yesterday" is missing.

**Comment by DylanPetrey** [comment]
Im going to tackle the yesterday issue

**Comment by DylanPetrey** [comment]
#98

**Comment by benvinegar** [comment]
"Today" was added in #53, and "Yesterday" in #98
