### ISSUE TITLE
Some sites not selectable if no events within current time range

### ISSUE THREAD

**Issue by benvinegar** [benvinegar/counterscale#43]
Example when 30 days (all sites selectable, because there is traffic within 30 days):  

<img width="565" alt="image" src="https://github.com/benvinegar/counterscale/assets/2153/cf8ed8ee-0c9a-4d34-a317-eff2d37fd36a">

But here's what happens when you choose 7 days:

<img width="573" alt="image" src="https://github.com/benvinegar/counterscale/assets/2153/15fa0766-8962-46b0-a5fc-bdf3aceaddff">

`benchmarking` disappears because it had no traffic during that period.

Expected behavior: `benchmarking` should still be selectable, even if there's no reported traffic over that interval.

**Comment by kandros** [comment]
I noticed it was happening here in https://github.com/kandros/counterscale/blob/a21f6fd2f172df75268d34a65e9713fa3aaa3c23/app/analytics/query.ts#L492
<img width="550" alt="image" src="https://github.com/benvinegar/counterscale/assets/4562878/98c859f3-08de-4123-8c46-93cb8e964d45">

the `WHERE timestamp > ${intervalSql}` is not finding `_sample_interval` relative to the site so it's not returned

**Comment by benvinegar** [comment]
Ah, yeah, I knew where the behavior was, I just wasn't sure what to do instead.

Maybe just select all sites with data within the past 90 days? (That's basically the entire data set, since CF Analytics Engine retention is 90 days at the moment.)
