### ISSUE TITLE
Abbreviate large numbers (e.g. 1.3k instead of 1300)

### ISSUE THREAD

**Issue by benvinegar** [benvinegar/counterscale#51]
At a certain point we don't really need to see the exact count.

What it looks like currently:

![image](https://github.com/benvinegar/counterscale/assets/2153/3d77c475-b5e8-4b74-9fa3-9413db2e03ea)

What it probably should look like:

![image](https://github.com/benvinegar/counterscale/assets/2153/11f0109f-ac05-496e-9df7-6c8d9a99e9f6)

**Comment by anurag-roy** [comment]
@benvinegar Can I take this up?

Follow up question, do we want the abbreviation only for Views, Visits, Visitors? Or do we want it everywhere including all the tables like Page, Referrer, etc?
