### ISSUE TITLE
Add loading indicators when data being fetched

### ISSUE THREAD

**Issue by benvinegar** [benvinegar/counterscale#54]
I notice that queries are taking a bit more time than in the past – it sometimes take 2-3 seconds to serve a new page during which there is no visual indicator to the user.

**Comment by kandros** [comment]
Would you prefer streaming data for specific components/sections using [remix defer](https://remix.run/docs/en/main/utils/defer) (I'm not sure if it works for client side navigations after the first) or a global visual indicator like [NProgress](https://ricostacruz.com/nprogress/)?

**Comment by kandros** [comment]
I've tried a simple opacity transition while navigating, I'm pretty effective to be honest

## After
https://github.com/benvinegar/counterscale/assets/4562878/4240171f-6767-4d71-956b-10f824333cad


## Before

https://github.com/benvinegar/counterscale/assets/4562878/b5b1d1ad-ca49-4ab8-a5eb-4016615f6385

**Comment by kandros** [comment]
> > I've tried a simple opacity transition while navigating
> 
> I think it looks great!

sending a PR 👌
