### ISSUE TITLE
UI overflowing bug

### ISSUE THREAD

**Issue by xuelink** [benvinegar/counterscale#69]
When it has longer text(url) component overflows in mobile or narrow browser, 
```css
word-wrap: break-word;
``` 
may fix this issue

> The `word-wrap: break-word;` CSS property specifies whether to break words when the content overflows the boundaries of its container.
Here's what it does:
`break-word`: Words that would overflow the container will break at the character level to fit within the container.
This is particularly useful when you have long strings of text (like URLs or file paths) that you want to fit within a container without overflowing.
Here's an example:
```html
<div style="width: 100px; border: 1px solid black; word-wrap: break-word;">
  ThisIsAVeryLongWordThatWouldNormallyOverflowTheContainer
</div>
```
> Without `word-wrap: break-word;`, the long word would overflow the 100px-wide container. With `word-wrap: break-word;`, the word breaks at the character level to fit within the container.

narrow browser:
<img width="548" alt="Screenshot 2024-04-14 at 6 02 37 PM" src="https://github.com/benvinegar/counterscale/assets/3280475/2dbcd733-7e9f-4dc9-9fa9-1d9d7454a0b8">

iphone:
![image](https://github.com/benvinegar/counterscale/assets/3280475/da698520-af81-41c1-995c-2ed5c3f23a67)

**Comment by benvinegar** [comment]
Thanks for submitting this. It's fixed in 47b9c415f28e2199beaf35f502ebcc56b9c7128b.
