### ISSUE TITLE
Discussion: omit query string to stop polluting path table?

### ISSUE THREAD

**Issue by benvinegar** [benvinegar/counterscale#73]
This is getting pretty irritating:

<img width="681" alt="image" src="https://github.com/benvinegar/counterscale/assets/2153/2522505d-cf81-4197-a611-82085527908a">

I think there are cases where you want query string, but you certainly don't want to see things like `utm_params`.

Options as I see it:
1. Strip the query string (distinct paths only)
2. Remove (and potentially store) known params like `utm_params`, `ref`, etc. from query string 
3. Do nothing

What would people like to see done here?

**Comment by drewrawitz** [comment]
I think the query parameters are useful data, but I agree that it makes the UI a tad messy. What if you show the distinct paths only, but have the ability to expand a top-level path to reveal the breakdown based on query parameter variations?

Here's a super quick and dirty mockup that I just did in the dev tools:

![Screenshot 2024-05-03 at 4 02 18 PM](https://github.com/benvinegar/counterscale/assets/5014932/f0e59e16-6d88-4662-b7e7-ddebc5bc5248)

And expanded:

![Screenshot 2024-05-03 at 4 01 54 PM](https://github.com/benvinegar/counterscale/assets/5014932/26a2fa71-0664-4869-aa32-32cd2effe1ed)

Ignore the last link, that would be grouped under the `/` path, but I was just focused on the `/dashboard` in this example!

**Comment by benvinegar** [comment]
I think because comparable products strip the query string, and because Counterscale promotes itself as being privacy-sensitive, it's worth doing the same (removed in c6493a5).
